### PR TITLE
All (yes / no) become ( yes / no )

### PR DESCRIPTION
**Pull request by Neustradamus**
All (yes / no) become ( yes / no ).

### CODE REVIEW

**Comment by dwd** [comment]
Not sure what this is trying to do; it's just adding spaces around the XHTML elements?

**Comment by agnauck** [comment]
@Neustradamus can you more details on why you are requesting to add a whitespace before the tag?
Which issue does this solve?

**Comment by Neustradamus** [comment]
I have updated, can you merge it?

**Comment by dwd** [comment]
But all this does is add a single space character, right? Why?

**Comment by Neustradamus** [comment]
In title -> (yes / no) becomes ( yes / no )
- One space before "yes"
- One space after "no"

Because currently there is a difference between "yes" and "no" in XMPP client (HTML):
- You can test with Psi and auto-capitalize function: "Psi -> Options -> Messages -> Input -> Automaticaly capitalize the first letter in a sentence".

Now it is same for "yes" and "no" and it is coherent with all the code.

**Comment by dwd** [comment]
OK, but:
* You haven't changed the message that's sent by Psi, just the text displayed. The links still send without any spaces (or should).
* You can now send "yes", "Yes", "YES", "       YES         ", and pretty much anything else thanks to @Ppjet6 and I anyway, so this ought to have no effect.

**Comment by Neustradamus** [comment]
Can you test current version?
I think you have not yet.

You will see the difference, when you click on:
- yes: you have "yes"
- no: you have "No"

You can see that the code is not complete.

After my change you have now "same":
- yes: you will have now "Yes"
- no: you will have always "No"

It will be perfect.

**Comment by Kev** [comment]
Closing:
 * Author refuses to test it.
 * Patch doesn't do what it says anyway.
 * Looks like capitalisation is a feature of Psi that the author has enabled.

**Pull request closed without merging**
